### PR TITLE
Update ocpu.js (Credits)

### PR DESCRIPTION
**Pull request by SparkyHeliolisk**
Update Credits

### CODE REVIEW

**Comment by SparkyHeliolisk** [comment]
Isn't he not an admin tho? He is only mod

**Comment by SparkyHeliolisk** [comment]
@zellman01 can you approve

**Comment by AlphaWind** [comment]
@zellman01 is it supposed to be events admin?

**Comment by SparkyHeliolisk** [comment]
@AlphaWind @zellman01 I've changed it to Events Lead

**Pull request merged**
