### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by zellman01**
This should fix all the possible errors that can be fixed with the eslint. The remaining errors I have no idea how to fix.

### CODE REVIEW

**Comment by zellman01** [comment]
Anyone have an idea on how to fix the remaining four eslint errors?

**Comment by DeathlyPlays** [comment]
@zellman01 iirc when I did this sort of thing I just eslintignored that file

**Comment by zellman01** [comment]
*has no idea what to do now*

**Comment by DeathlyPlays** [comment]
Oh, TypeScript eslint is where I quit even trying its really dumb

**Comment by zellman01** [comment]
Then how da heck do I fix it?

**Comment by zellman01** [comment]
I'll ad them to the config.js file when I update the server

**Pull request merged**
